{"uuid": "a3330279-310f-4b42-9c87-1da50773c9a7", "children": ["8cbb98a7-4e54-498c-a594-d593b0be9756"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff74704fea5+79173]\n\tGetHandleVerifier [0x0x7ff74704ff00+79264]\n\t(No symbol) [0x0x7ff746e09e5a]\n\t(No symbol) [0x0x7ff746de20f1]\n\t(No symbol) [0x0x7ff746e9017e]\n\t(No symbol) [0x0x7ff746eb0922]\n\t(No symbol) [0x0x7ff746e88743]\n\t(No symbol) [0x0x7ff746e514c1]\n\t(No symbol) [0x0x7ff746e52253]\n\tGetHandleVerifier [0x0x7ff74731a2dd+3004797]\n\tGetHandleVerifier [0x0x7ff74731472d+2981325]\n\tGetHandleVerifier [0x0x7ff747333380+3107360]\n\tGetHandleVerifier [0x0x7ff74706aa2e+188622]\n\tGetHandleVerifier [0x0x7ff7470722bf+219487]\n\tGetHandleVerifier [0x0x7ff747058df4+115860]\n\tGetHandleVerifier [0x0x7ff747058fa9+116297]\n\tGetHandleVerifier [0x0x7ff74703f558+11256]\n\tBaseThreadInitThunk [0x0x7ffda8bf7374+20]\n\tRtlUserThreadStart [0x0x7ffdaa1fcc91+33]\n\n", "trace": "  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\test_招聘审批流程.py\", line 69, in login\n    allure.attach(driver.get_screenshot_as_png(), name=\"登录失败截图\",attachment_type=allure.attachment_type.PNG)\n                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1019, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1029, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\Desktop\\test\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1751938193917, "stop": 1751938195518}], "start": 1751938193917, "stop": 1751938195766}