{"uuid": "5d80b2ea-4841-4854-aa81-cc7931138cef", "children": ["375efdbc-181f-4e1b-b719-25f9dbbb3d8c"], "befores": [{"name": "cleanup", "status": "passed", "start": 1753511062136, "stop": 1753511062136}], "afters": [{"name": "cleanup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <unknown>: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.\n  (Session info: chrome=108.0.5359.125)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00EEF243]\n\t(No symbol) [0x00E77FD1]\n\t(No symbol) [0x00D6D04D]\n\t(No symbol) [0x00D6FD34]\n\t(No symbol) [0x00D6FBE5]\n\t(No symbol) [0x00D70565]\n\t(No symbol) [0x00DCD47C]\n\t(No symbol) [0x00DB858C]\n\t(No symbol) [0x00DCC9EB]\n\t(No symbol) [0x00DB8386]\n\t(No symbol) [0x00D9163C]\n\t(No symbol) [0x00D9269D]\n\tGetHandleVerifier [0x01189A22+2655074]\n\tGetHandleVerifier [0x0117CA24+2601828]\n\tGetHandleVerifier [0x00F98C0A+619850]\n\tGetHandleVerifier [0x00F97830+614768]\n\t(No symbol) [0x00E805FC]\n\t(No symbol) [0x00E85968]\n\t(No symbol) [0x00E85A55]\n\t(No symbol) [0x00E9051B]\n\tBaseThreadInitThunk [0x76EFFCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D582AE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D5827E+238]\n\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\test\\conftest.py\", line 9, in cleanup\n    driver.execute_script(\"window.localStorage.clear();\")\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1753511062140, "stop": 1753511062187}], "start": 1753511062136, "stop": 1753511062187}