{"uuid": "5f232066-51da-4948-a5e5-69a3249c1b43", "children": ["b83ccdb1-cd63-46ab-bf28-cc2bb233e049", "172ed2d4-50d6-43f7-828e-c3f2c51ca87f"], "befores": [{"name": "cleanup", "status": "passed", "start": 1753511455108, "stop": 1753511455108}], "afters": [{"name": "cleanup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7e301fea5+79173]\n\tGetHandleVerifier [0x0x7ff7e301ff00+79264]\n\t(No symbol) [0x0x7ff7e2dd9c8c]\n\t(No symbol) [0x0x7ff7e2e205ef]\n\t(No symbol) [0x0x7ff7e2e58832]\n\t(No symbol) [0x0x7ff7e2e53233]\n\t(No symbol) [0x0x7ff7e2e522f9]\n\t(No symbol) [0x0x7ff7e2da5fc5]\n\tGetHandleVerifier [0x0x7ff7e32ea2dd+3004797]\n\tGetHandleVerifier [0x0x7ff7e32e472d+2981325]\n\tGetHandleVerifier [0x0x7ff7e3303380+3107360]\n\tGetHandleVerifier [0x0x7ff7e303aa2e+188622]\n\tGetHandleVerifier [0x0x7ff7e30422bf+219487]\n\t(No symbol) [0x0x7ff7e2da5036]\n\tGetHandleVerifier [0x0x7ff7e3403c78+4158232]\n\tBaseThreadInitThunk [0x0x7ffab4797374+20]\n\tRtlUserThreadStart [0x0x7ffab63dcc91+33]\n\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\test\\conftest.py\", line 8, in cleanup\n    driver.delete_all_cookies()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 779, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1753511458230, "stop": 1753511458236}], "start": 1753511455108, "stop": 1753511458236}